ITEM.name = "Anti-radiation drugs"
ITEM.description = "Features anti-radiation signs on the package."
ITEM.longdesc = "Mexaminum radiation protection drugs are common in the Zone. When used, this drug induces contraction of peripheral blood vessels and oxygen deprivation, which serve to treat and prevent radiation exposure. The drug does not have severe side effects, although isolated cases of mild nausea, dizziness, cramps and stomach pain have been reported."
ITEM.model = "models/kek1ch/dev_antirad.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medical"
ITEM.quantMax = 2
ITEM.quantity = 2
ITEM.sound = "stalkersound/inv_eat_pills.mp3"
ITEM.price = "1000"
ITEM.flag = "1"
ITEM.weight = 0.05
ITEM.useName = "Swallow"
ITEM.useText = {"opens an ", " and swallows one."}