ITEM.name = "ECS Amethyst Stimpack"
ITEM.description = "A stimpack made by the ECS program of the 'Gem' variety. It's labeled as 'Amethyst'."
ITEM.longdesc = "Heals minor chemical/thermal burns, at the cost of thinning the blood of the user.\n\n Resets hotspot exposure for Thermal/Chemical.\n +3 Chemical and Thermal for ten minutes. \n Increases bleed tier (if a bleed is suffered) by one."
ITEM.model = "models/warz/items/syringe.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medical"
ITEM.restore = 4
ITEM.radrem = 2
ITEM.sound = "stalkersound/inv_bandage.mp3"
ITEM.price = "45000"
ITEM.flag = "1"
ITEM.useName = "Inject"
ITEM.useText = {"opens a ", " and injects it."}