ITEM.name = "ECS Adamantite Stimpack"
ITEM.description = "A stimpack made by the ECS program of the 'Mineral' variety. It's labeled as 'Adamantite'"
ITEM.longdesc = "+1 Tier of Impact for eight turns up to T4.\n\n Heavily staggers user for use (Migraine), decreases to moderate stagger after effects wear off (Headache)." 
ITEM.model = "models/warz/items/syringe.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medical"
ITEM.quantMax = 1
ITEM.quantity = 1
ITEM.restore = 4
ITEM.radrem = 2
ITEM.sound = "stalkersound/inv_bandage.mp3"
ITEM.price = "30000"
ITEM.flag = "1"
ITEM.useName = "Inject"
ITEM.useText = {"opens a ", " and injects it."}