ITEM.name = "Antidote"
ITEM.model = "models/kek1ch/drug_antidot.mdl"
ITEM.description = "A combination drug that counter-acts poisoning and chemical weapons inhalation. +1 Chem protection tier (Max 2) for 1 hour and resets Chem hotspot. Makes user experience vertigo at random points, making climbing and acrobatic stunts impossible."
ITEM.category = "Medical"
ITEM.quantMax = 5
ITEM.quantity = 1
ITEM.price = 3000
ITEM.flag = "1"
ITEM.sound = "stalker/interface/inv_eat_pills_effect.ogg"
ITEM.useName = "Swallow"
ITEM.useText = {"opens an ", " and swallows one."}