ITEM.name = "Bandage"
ITEM.description = "A small bandage for wounds."
ITEM.longdesc = "A normal elastic bandage used to stop bleeding and prevent infection of wounds. For regular bleeding, carefully apply the bandage to the wound. For arterial bleeding, urgently tie the bandage around the affected area."
ITEM.model = "models/kek1ch/dev_bandage.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medical"
ITEM.restore = 15
ITEM.sound = "stalkersound/inv_bandage_2p9.mp3"
ITEM.price = "500"
ITEM.flag = "1"
ITEM.weight = 0.05
ITEM.stopsBleed = true
ITEM.useName = "Wrap"
ITEM.useText = {"unwraps and ties a ", " around their wound."}