ITEM.name = "Army Dressing"
ITEM.description = "A packaged Ukrainian Military Dressing."
ITEM.longdesc = "A normal elastic bandage used to stop bleeding and prevent infection of wounds. For regular bleeding, carefully apply the bandage to the wound. For arterial bleeding, urgently tie the bandage around the affected area."
ITEM.model = "models/illusion/eftcontainers/armybandage.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medical"
ITEM.restore = 10
ITEM.sound = "stalkersound/inv_bandage_2p9.mp3"
ITEM.price = "1000"
ITEM.flag = "1"
ITEM.weight = 0.1
ITEM.quantity = 2
ITEM.stopsBleed = true
ITEM.useName = "Wrap"
ITEM.useText = {"unwraps and ties a ", " around their wound."}