ITEM.name = "ECS Diamond Stimpack"
ITEM.description = "A stimpack made by the ECS program of the 'Combination' variety. It's labeled as 'Diamond'"
ITEM.longdesc = "A general cure all but at a severe cost on the body... Cures extreme bleeds through blood coagulation, resets hotspot exposure, general pain relief, surges the body with adrenaline. Can bring an incapacitated and heavily injured individual into a fighting state, or allow them to seek immediate treatment. User is easily frenzied and incapable of advanced thought. Grants a +25 to Strength Rolls."
ITEM.model = "models/warz/items/syringe.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medical"
ITEM.quantMax = 1
ITEM.quantity = 1
ITEM.restore = 4
ITEM.radrem = 2
ITEM.sound = "stalkersound/inv_bandage.mp3"
ITEM.price = "100000"
ITEM.flag = "1"
ITEM.useName = "Inject"
ITEM.useText = {"opens a ", " and injects it."}
