ITEM.name = "Large First-Aid Kit"
ITEM.description = "A red pack with an abundancy of relief supplies."
ITEM.longdesc = "A civilian-grade first-aid medical kit equipped with a decent amount of low-tier supplies to patch up basic burns, scrapes, cuts, and aches."
ITEM.model = "models/illusion/eftcontainers/salewa.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.category = "Medical"
ITEM.restore = 3
ITEM.sound = "stalkersound/inv_bandage.mp3"
ITEM.price = "4000"
ITEM.flag = "1"
ITEM.quantity = 6
ITEM.weight = 1
ITEM.stopsBleed = true