ITEM.name = "Scientific First-Aid Kit"
ITEM.description = "Medkit used by ecologists."
ITEM.longdesc = "A medical kit designed specifically for use in the Zone.\nThe kit contains products for handling wounds, as well as preventing the development of radiation poisoning and reducing accumulated radiation in the body."
ITEM.model = "models/kek1ch/dev_aptechka_mid.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medical"
ITEM.quantMax = 3
ITEM.quantity = 3
ITEM.restore = 4
ITEM.radrem = 2
ITEM.sound = "stalkersound/inv_bandage.mp3"
ITEM.price = "8000"
ITEM.flag = "1"
ITEM.weight = 0.4
ITEM.stopsBleed = true