ITEM.name = "Psi-Block"
ITEM.model = "models/stalker/item/medical/psy_pills.mdl"
ITEM.description = "Drug designed to protect the body from nervous overload by means of strong emotions or psi-attacks. +1 Psi protection tier (max total 2) for 1 hour and resets Psi hotspot timer. Makes user sluggish (+1 second staggered/stunned) for the duration."
ITEM.category = "Medical"
ITEM.price = 6000
ITEM.flag = "1"
ITEM.sound = "stalker/interface/inv_eat_pills_effect.ogg"
ITEM.useName = "Swallow"
ITEM.useText = {"opens a ", " and swallows one."}