ITEM.name = "ECS Pearl Stimpack"
ITEM.description = "A stimpack made by the ECS program of the 'Gem' variety. It's labeled as 'Pearl'"
ITEM.longdesc = "All-around healer, surges the target with adrenaline before they temporarily lose consciousness and then will awake with a Moderate Stagger or worse.\n\n Immune to stun/incap for three friendly turns. Results in incap on fourth friendly turn. Results in 5 day Decreased Motor-Function TI."
ITEM.model = "models/warz/items/syringe.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medical"
ITEM.restore = 4
ITEM.radrem = 2
ITEM.sound = "stalkersound/inv_bandage.mp3"
ITEM.price = "50000"
ITEM.flag = "1"
ITEM.stopsBleed = true