ITEM.name = "ECS Ruby Stimpack"
ITEM.description = "A stimpack made by the ECS program of the 'Gem' variety. It's labeled as 'Ruby'"
ITEM.longdesc = "A stimpack designed to greatly degree the bleed at the cost of severe caloric loss.\n\n Heals Heavy Bleeds immediately.\n -3sec Movement, gradually decreases every two turns"
ITEM.model = "models/warz/items/syringe.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medical"
ITEM.restore = 4
ITEM.radrem = 2
ITEM.sound = "stalkersound/inv_bandage.mp3"
ITEM.price = "25000"
ITEM.flag = "1"
ITEM.quantity = 1
ITEM.weight = 1
ITEM.stopsBleed = true