ITEM.name = "Vinca"
ITEM.description = "A drug that causes blood to coagulate for open wounds."
ITEM.longdesc = "An ingestible drug to counter-act medium strength bleeding by means of accelerating clotting and increasing blood thickness."
ITEM.model = "models/ethprops/medical/psy_pills.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medical"
ITEM.sound = "stalker/interface/inv_eat_pills_effect.ogg"
ITEM.price = "8000"
ITEM.flag = "1"
ITEM.quantity = 4
ITEM.weight = 0.1
ITEM.stopsBleed = true
ITEM.useName = "Swallow"
ITEM.useText = {"opens a ", " and swallows one."}