ITEM.name = "Vasopressors"
ITEM.description = "A heart medicine used to increase blood pressure in case of heat stroke."
ITEM.longdesc = "In cases of severe heat stroke, the body's blood vessels will dilate and cause weakness & dizziness. Vasopressants can be used to temporarily mitigate such weakness and keep a stalker's body strong enough to circumvent thermal formations, but has a side effect of making open wounds bleed more as a result. Rarely used by rookies, and mostly by experienced stalkers who can't afford better equipment. \n\nResets Thermal hotspot when consumed\nFor one hour:\n+1 Thermal Tier (Max 2)\nBleeding +1"
ITEM.model = "models/ethprops/medical/psy_pills.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Medical"
ITEM.sound = "stalker/interface/inv_eat_pills_effect.ogg"
ITEM.price = "3000"
ITEM.flag = "1"
ITEM.weight = 0.1
ITEM.useName = "Swallow"
ITEM.useText = {"opens a ", " and swallows one."}