ITEM.name = "EMT Bag"
ITEM.model = "models/illusion/eftcontainers/grizzly.mdl"
ITEM.longdesc = "A medic's large trauma care bag is enough to stabilize wounded in the field and deliver them to a medical post, where they can begin recovery."
ITEM.description = "A kit-bag with various instruments for rapid life-saving purposes."
ITEM.category = "Medical"
ITEM.flag = "1"
ITEM.price = 10000
ITEM.width = 1
ITEM.height = 1