ITEM.name = "7.62x39mm Belt Match Grade"
ITEM.model = "models/silver/stalker/items/item_762x39belt.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "7.62x39MMB -MG-"
ITEM.description = "A belt and drum that contains %s rounds of 7.62x39mm. The rounds are of certified Match quality."
ITEM.category = "Ammunition"
ITEM.price = 4800
ITEM.flag = "4"
ITEM.ammoAmount = 100
ITEM.weight = 0.025
ITEM.isAmmo = true
