ITEM.name = "Cannabis Joint"
ITEM.description = "A joint of weed, complete with a filter."
ITEM.longdesc = "It smells wacky, weighs about a gram, makes your throat dry, your eyes watery, and stupid things more funny when you smoke it. A general system depressant, it can be used to help aid exposure to psi either before or after, though it may make your time to react a bit slower or make you take a little bit longer due to your impaired state. Lasts 30 minutes.\n\n +1 Psi\n -5/10 to rolls"
ITEM.model = "models/ethprops/consumable/joint.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.category = "Consumables"
ITEM.sound = "stalkersound/inv_smoke.mp3"
ITEM.price = "1500"
ITEM.flag = "1"
ITEM.quantity = 1
ITEM.weight = 0.1
ITEM.useText = {"takes out a ", " and smokes it."}