ITEM.name = "PSO-1"
ITEM.description = "Russian optic sight. 4.0x magnification. Delta type sight."
ITEM.category = "Attachments"
ITEM.width = 2
ITEM.height = 1
ITEM.model = "models/cw2/attachments/pso.mdl"
ITEM.upgradeIcon = Material("materials/vgui/ui/stalker/weaponupgrades/4xmag.png")
ITEM.slot = 1
--ITEM.busflag = "SPECIAL3_1"
ITEM.price = 9500 
ITEM.Range = 10
ITEM.isAttachment = true
ITEM.weight = 0.65
ITEM.attSearch = { "cw_sil_pso1_scope"}
ITEM.flag = "3"