ITEM.name = "ZF4 Scope"
ITEM.description = "Old German optical sight. 3.0x magnification."
ITEM.category = "Attachments"
ITEM.width = 2
ITEM.height = 1
ITEM.model = "models/cw2/attachments/pso.mdl"
ITEM.upgradeIcon = Material("materials/vgui/ui/stalker/weaponupgrades/4xmag.png")
ITEM.slot = 1
--ITEM.busflag = "SPECIAL3_1"
ITEM.price = 8500 
ITEM.Range = 10
ITEM.isAttachment = true
ITEM.weight = 0.65
ITEM.attSearch = { "cw_sil_zf4"}
ITEM.flag = "3"